# Generated by Django 4.1.1 on 2023-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(default=2, max_length=50, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
