# Generated by Django 4.1.1 on 2023-01-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_street_city_alter_street_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('shop_city', models.CharField(max_length=50, verbose_name='Город')),
                ('shop_street', models.CharField(max_length=50, verbose_name='Улица')),
                ('shop_began_work', models.DateTimeField()),
                ('shop_end_work', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
