# Generated by Django 4.1.1 on 2023-01-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shop_shop_street_alter_shop_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_began_work',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_end_work',
            field=models.TimeField(),
        ),
    ]
